import torch
import numpy.typing as npt

def random_vector(
    rng: torch.Generator = ..., n: int = ...
) -> torch.Tensor: ...
def random_axis_angle(rng: torch.Generator = ...) -> torch.Tensor: ...
def random_compact_axis_angle(rng: torch.Generator = ...) -> torch.Tensor: ...
def random_quaternion(rng: torch.Generator = ...) -> torch.Tensor: ...
def random_matrix(
    rng: torch.Generator = ...,
    mean: npt.ArrayLike = ...,
    cov: npt.ArrayLike = ...,
) -> torch.Tensor: ...
