import numpy as np
import numpy.typing as npt
import torch.types as tct
from typing import Tuple

def check_axis_index(name: str, i: int): ...
def norm_vector(v: tct.Tensor) -> tct.Tensor: ...
def perpendicular_to_vectors(
    a: tct.Tensor, b: tct.Tensor
) -> tct.Tensor: ...
def perpendicular_to_vector(a: tct.Tensor) -> tct.Tensor: ...
def angle_between_vectors(
    a: tct.Tensor, b: tct.Tensor, fast: bool = ...
) -> float: ...
def vector_projection(a: tct.Tensor, b: tct.Tensor) -> tct.Tensor: ...
def plane_basis_from_normal(
    plane_normal: tct.Tensor,
) -> Tuple[tct.Tensor, tct.Tensor]: ...
